name: Build develop

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache APT packages
        uses: actions/cache@v2
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-${{ hashFiles('**/install.sh') }}
          restore-keys: |
            ${{ runner.os }}-apt-

      - name: Install dependencies
        if: steps.cache-apt.outputs.cache-hit != 'true'
        run: |
          sudo sh install.sh
          sudo chown -R $USER:$USER /var/cache/apt/archives

      - name: Build project
        run: make

      - name: "Check ISO"
        run: ls boot/os.iso
