name: Build develop branch
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache APT Packages
      uses: awalsh128/cache-apt-pkgs-action@v1.3.1
      with:
        packages: build-essential gcc-i686-linux-gnu binutils grub-common xorriso mtools grub-pc-bin nasm qemu-system bochs libsdl2-dev libcanberra-gtk-module libcanberra-gtk3-module
        version: 1.0
        
    - name: Run build
      run: make

    - name: Verify
      run: ls -l boot/os.iso && file boot/os.iso

    - name: Checksum
      run: sha256sum boot/os.iso
